package constants

const (
	BATCH_DECLINED     = "Batch is declined"
	DECLINED           = "DECLINED"
	BATCH_CREATED      = "Batch created"
	BATCH_REJECTED     = "Batch rejected"
	NO_ORDER_FOUND     = "No order found"
	RETURNED_TO_WH     = "Returned to wh"
	BATCH_ACCEPTED     = "Batch is accepted"
	START_PICKUP       = "Driver start pickup order"
	ARRIVED_AT_PICKUP  = "Driver arrived at pickup order"
	PARCEL_PICKUP      = "Driver picked up the order"
	PICKUP_FAILED      = "Driver pick up failed the order"
	START_DROPOFF      = "Driver start dropoff order"
	ARRIVED_AT_DROPOFF = "Driver arrived at dropoff order"
	DELIVERED          = "Driver delivered the order"
	DELIVERY_FAILED    = "Driver failed the order"
	START_RETURN       = "Driver start return the order"
	ARRIVED_AT_SENDER  = "Driver arrived the sender the order for return"
	RETURNED_TO_SENDER = "Driver returned order"
	ACCEPTED_LABEL     = "ACCEPTED"
	START_PICKUP_LABEL = "START_PICKUP"
	BATCH_RECEIVED     = "Batch received by the driver"
	PN_RECEIVED        = "Batch assignment pn received by the driver"
	BATCH_SEEN         = "Batch seen"
	BATCH_SEEN_NOTES   = "Batch seen by the driver"
)
